### PR TITLE
Fix blueprint, bump packages and speed up CI

### PR DESCRIPTION
**Pull request by pitmonticone**
- [x] Add Mathlib-like 100-characters ruler to enhance readability
- [x] Fix LaTeX warning: "Reference `lem:recurrence_iff_finite_limit_integral' on page 1 undefined on input line 48"
- [x] Fix `hyperref` warning: "Token not allowed in a PDF string (Unicode)"
- [x]  Fix a typo in `overview.tex`
- [x] Bump `mathlib` and `doc-gen4` to minimise disk space usage 
- [x] Add files to `.gitignore`
- [x] Minimise imports to speed up docs build in GitHub actions (from 33 to 11 minutes)
- [x] Add `push.yml` and `push-pr.yml` CI config files and remove `blueprint.yml`
- [x] Cleanup and golfing

### CODE REVIEW

**Comment by xhalo32** [comment]
Hi,

Thanks for the pull request! Your GitHub workflows changes look good and we would have preferred if they were separated to their own PR as they are not related to the Lean and TeX changes you made.

I will cherry-pick your GitHub workflow changes and return to the other changes after that.

**Comment by pitmonticone** [comment]
@xhalo32 I have just pushed two minor changes. Now it's ready to be merged.

If you prefer, I can open multiple PRs.

**Comment by xhalo32** [comment]
Sorry, I missed your message... We reviewed your changes with @YaelDillies and cherry-picked the CI-related ones into their own commit https://github.com/alma-n/Polya-lean/commit/74a7e40ba0843dd0abc1f66617d377e800dd459b.

`Polya/{Basic,ForAlli}.lean` were leftovers from earlier and will be removed shortly so the only things "left in your PR" are the TeX changes. I will close this one (as the CI stuff is merged); please open a new one called "Minor TeX and Lean changes."

Sorry about the mess.

**Comment by pitmonticone** [comment]
Sure @xhalo32, no problem.

**Comment by pitmonticone** [comment]
@xhalo32 Done #8

**Pull request closed without merging**
